name: diabetes
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.0
  - pytorch=1.7.0
  - torchvision=0.8.1
  - numpy>=1.20.3
  - ipython
  - jupyterlab
  - pandas
  - matplotlib
  - scikit-learn
  - wandb
