wandb_version: 1

ae_encoder:
  desc: null
  value: skilled-universe-10
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1733172096.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
